spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bankDb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update


bank:
  app:
    jwtHeaderName: Authorization
    jwtSecret: GtFPkqzKAbks8cswXPXN


server:
  error:
    include-message: always

